#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <ctime>
#include <cfloat>
#include <climits>
#include <cstdint>
#include <cmath>
#include <cstdlib>
#include <cstdio>
#include <cerrno>
#include <cstring>
#include <algorithm>
#include <stdexcept>
#include "../../src/jansson.h"
#ifndef JANSSON_PRIVATE_CONFIG_HPP
#define JANSSON_PRIVATE_CONFIG_HPP

#define HAVE_UNISTD_H 1
#define HAVE_SCHED_H 1

#endif /* JANSSON_PRIVATE_CONFIG_HPP */
