#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <cerrno>
#include <cassert>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <cstddef>
#include <cwctype>
#include <cwchar>
#include <cctype>
#include <ctime>
#include <cfloat>
#include <climits>
#include <cstdint>
#include <cmath>
#include <cstdlib>
#include <cstdio>
#include <cerrno>
#include <cstring>
#include <algorithm>
#include <stdexcept>
#include "../../src/jansson.h"
/*
 * Copyright (c) 2009-2016 Petri Lehtinen <petri@digip.org>
 *
 * Jansson is free software; you can redistribute it and/or modify
 * it under the terms of the MIT license. See LICENSE for details.
 */

#ifndef STRBUFFER_H
#define STRBUFFER_H

#include "jansson.hpp"
#include <stdlib.h>

typedef struct {
    char *value;
    size_t length; /* bytes used */
    size_t size;   /* bytes allocated */
} strbuffer_t;

int strbuffer_init(strbuffer_t *strbuff) JANSSON_ATTRS((warn_unused_result));
void strbuffer_close(strbuffer_t *strbuff);

void strbuffer_clear(strbuffer_t *strbuff);

const char *strbuffer_value(const strbuffer_t *strbuff);

/* Steal the value and close the strbuffer */
char *strbuffer_steal_value(strbuffer_t *strbuff);

int strbuffer_append_byte(strbuffer_t *strbuff, char byte);
int strbuffer_append_bytes(strbuffer_t *strbuff, const char *data, size_t size);

char strbuffer_pop(strbuffer_t *strbuff);

#endif
