#ifndef JANSSON_PRIVATE_CONFIG_H
#define JANSSON_PRIVATE_CONFIG_H

#define JSON_HAVE_ATOMIC_BUILTINS 1
#define JSON_HAVE_POSIX_FCNTL 1
#define JSON_HAVE_LOCALECONV 1
#define JSON_HAVE_LOCALE_H 1
#define JSON_HAVE_SETLOCALE 1
#define JSON_HAVE_STRTOLL 1
#define JSON_HAVE_STRTOULL 1
#define JSON_HAVE_STRTOF 1
#define JSON_HAVE_STRTOF 1
#define JSON_HAVE_LOCALECONV 1
#define JSON_LONGLONG 1
#define JSON_LONG_LONG 1
#define JSON_INTEGER_FORMAT "lld"
#define JSON_UINTEGER_FORMAT "llu"
#define JSON_UINT_MAX UINT_MAX
#define JSON_ULONG_MAX ULONG_MAX
#define JSON_SIZE_MAX SIZE_MAX

#endif // JANSSON_PRIVATE_CONFIG_H
